format:
  line_width: 90
  tab_size: 2
  use_tabchars: false
  dangle_parens: false
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 6
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  command_case: 'lower'
  keyword_case: 'upper'

markup:
  enable_markup: true
  first_comment_is_literal: false
  literal_comment_pattern: null
  bullet_char: '*'
  enum_char: '.'

lint:
  disabled_codes: []
  function_pattern: '[0-9a-z_]+'
  macro_pattern: '[0-9A-Z_]+'
  global_var_pattern: '[A-Z][0-9A-Z_]+'
  internal_var_pattern: '_[A-Z][0-9A-Z_]+'
  local_var_pattern: '[a-z][a-z0-9_]+'
  max_line_length: 90
  min_statement_spacing: 1
  max_statement_spacing: 2